name: Bug Report
description: Report a bug in create-nextjs-stack
labels: ["bug", "triage"]
body:
  - type: input
    id: version
    attributes:
      label: Package Version
      description: "Run: npx create-nextjs-stack --version"
      placeholder: "0.2.0"
    validations:
      required: true

  - type: dropdown
    id: template
    attributes:
      label: Template Type
      options:
        - Web
        - Admin
        - Full-Stack
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: "Run: node --version"
      placeholder: "v20.11.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "macOS 14.2 / Windows 11 / Ubuntu 24.04"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? What did you expect?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the issue
      value: |
        1. Run `npx create-nextjs-stack my-app --template web`
        2. ...
        3. ...
    validations:
      required: true
